server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${uri}
    username: ${username}
    password: ${password}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # 첫 배포 이후 validate 으로 수정
    open-in-view: false
    show-sql: true
    generate-ddl: true

  jwt:
    secret: ${jwt-secret}
    token:
      access-expiration-time: ${jwt-access-expiration-time}
      refresh-expiration-time: ${jwt-refresh-expiration-time}

  data:
    redis:
      host: ${redis-host-post}
      port: 6379
