server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${url}
    username: ${username}
    password: ${password}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    generate-ddl: true

  jwt:
    secret: ${JWT_SECRET}
    token:
      access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
      refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

