server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres!

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    generate-ddl: true

  jwt:
    secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
    token:
      access-expiration-time: 999999999
      refresh-expiration-time: 999999999

  data:
    redis:
      host: localhost
      port: 6379
