cloud:
  aws:
    s3:
      bucket: sponus
      folder: images/  # upload prefix
    stack:
      auto: false # CloudFormation 비활성화
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIASX3QJE3XPT7GVA3Y
      secretKey: 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
