@masterToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzcG9udXNAZ21haWwuY29tIiwiYXV0aCI6IlNUVURFTlQiLCJpYXQiOjE3MDU4MzQ2MTksImV4cCI6MTcwNjgzNDYxOX0.XO8ydia0RB1eVGXrA7nBeP5AND2Ui4ivK26DEldZLnE

### 회원가입
POST http://localhost:8080/api/v1/organizations/join
Content-Type: application/json

{
  "name": "팀 스포너스",
  "email": "sponus@gmail.com",
  "password": "password1234",
  "location": "none",
  "organizationType": "STUDENT",
  "suborganizationType": "STUDENT_COUNCIL",
  "managerName": "이가은",
  "managerPosition": "Project Manager",
  "managerEmail": "test@gmail.com",
  "managerPhone": "01012345678",
  "managerAvailableDay": "월-금",
  "managerAvailableHour": "15:00-18:00",
  "managerContactPreference": "EMAIL"
}

### 로그인
POST http://localhost:8080/api/v1/organizations/login
Content-Type: application/json

{
  "email": "sponus@gmail.com",
  "password": "password1234"
}

### 공고 생성
POST http://localhost:8080/api/v1/announcements
Authorization: Bearer {{masterToken}}
Content-Type: application/json

{
  "title": "무신사 스폰서십",
  "type": "SPONSORSHIP",
  "category": "MARKETING",
  "content": "무신사 스폰서십을 진행할 대학교 학생회를 모집합니다."
}

### 공고 상세 조회
GET http://localhost:8080/api/v1/announcements/1
Authorization: Bearer {{masterToken}}

### 공고 상태별 목록 조회
GET http://localhost:8080/api/v1/announcements/status?status=POSTED
Authorization: Bearer {{masterToken}}

### 공고 수정
PATCH http://localhost:8080/api/v1/announcements/1
Authorization: Bearer {{masterToken}}
Content-Type: application/json

{
  "title": "스포너스 스폰서십",
  "type": "SPONSORSHIP",
  "category": "MARKETING",
  "content": "스포너스 스폰서십을 진행할 대학교 학생회를 모집합니다."
}

### 공고 삭제 (생성한 단체만 삭제 가능)
DELETE http://localhost:8080/api/v1/announcements/1
Authorization: Bearer {{masterToken}}

### 보고서 작성
POST http://localhost:8080/api/v1/reports
Content-Type: application/json

{
  "title": "무신사 스폰서십",
  "content": "무신사 스폰서십을 진행했습니다.",
  "files": []
}

### 보고서 조회
GET http://localhost:8080/api/v1/reports/0


### 공고 검색
GET http://localhost:8080/api/v1/announcements?search=무신사

### 내 조직 조회
GET http://localhost:8080/api/v1/organizations/me
Authorization: Bearer {{masterToken}}

### 내 조직 수정
PATCH http://localhost:8080/api/v1/organizations/me
Authorization: Bearer {{masterToken}}
Content-Type: application/json

{
  "name": "팀 스포너스 업데이트!!!!",
  "email": "sponus@gmail.com 업데이트!!!!",
  "password": "password1234 업데이트!!!!",
  "location": "none 업데이트!!!!",
  "organizationType": "COMPANY",
  "suborganizationType": "CLUB",
  "managerName": "이가은",
  "managerPosition": "Project Manager",
  "managerEmail": "test@gmail.com",
  "managerPhone": "01012345678",
  "managerAvailableDay": "월-금",
  "managerAvailableHour": "15:00-18:00",
  "managerContactPreference": "EMAIL 업데이트!!!!"
}

### 내 조직 수정 2
PATCH http://localhost:8080/api/v1/organizations/me
Authorization: Bearer {{masterToken}}
Content-Type: application/json

{
  "name": "팀 스포너스 업데이트!!!!2"
}

### 내 조직 삭제 [soft delete] (OrganizationStatus = INACTIVE)
DELETE http://localhost:8080/api/v1/organizations/me
Authorization: Bearer {{masterToken}}

### 조직 조회
GET http://localhost:8080/api/v1/organizations/1
Authorization: Bearer {{masterToken}}

### 태그 생성
POST http://localhost:8080/api/v1/tags
Authorization: Bearer {{masterToken}}
Content-Type: application/json

{
  "name": "태그 name test2"
}

### 태그 수정 기능(todo: 테스트 필요)
PATCH http://localhost:8080/api/v1/tags/1
Authorization: Bearer {{masterToken}}
Content-Type: application/json

{
  "name": "태그 수정"
}

