spring.config.activate.on-profile: local

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/sponus
    username: root
    password: root1234!
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
#    generate-ddl: true
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:db/data.sql
#      schema-locations: classpath:db/schema.sql

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
