#spring:
#  profiles:
#    active: local
#    include: secret, db, s3
#
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB

server:
  port: 8080

spring:
  profiles:
    group:
      "local": "db, s3, secret"
      "prod": "db, s3"
    default: local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
