spring:
  profiles:
    active: local
    include: secret, db

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#server:
#  port: 8080

#spring:
#  profiles:
#    group:
#      "local": "db, secret"
#      "prod": "db, prod"
#    default: local

#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB
