server:
  port: 8080

spring:
  profiles:
    group:
      "local": "db, s3, secret"
      "prod": "db, s3, redis"
    default: local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
