mail:
  smtp:
    port: ${EMAIL_PORT}
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false

AdminMail:
  id: ${ADMIN_EMAIL_ID}
  password: ${ADMIN_EMAIL_PASSWORD}
