server:
  port: 8080

spring:
  jwt:
    secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
    token:
      access-expiration-time: 999999999
      refresh-expiration-time: 999999999

  data:
    redis:
      host: localhost
      port: 6379
