name: CD

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ## gradle 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      ## create application.yml
      - name: make application-secret.yml
        run: |
          mkdir -p ./api/src/main/resources
          touch ./api/src/main/resources/application-secret.yml
        shell: bash
      - name: deliver application-secret.yml
        run: echo "${{ secrets.APPLICATION_SECRET }}" > ./api/src/main/resources/application-secret.yml
        shell: bash

      # 빌드 및 테스트 단계.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test

      # push 하기 위해 로그인
      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #도커 빌드 & 이미지 push
      - name: Docker build & Push
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/sponus-docker .
          docker push ${{ secrets.DOCKER_USERNAME }}/sponus-docker

      # Docker 파일을 EC2 서버에 배포
      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            if [ ! -z "$(docker ps -q)" ]; then
              docker stop $(docker ps -q)
            fi

            if [ ! -z "$(docker ps -aq)" ]; then
              docker rm $(docker ps -aq)
            fi
            
            if [ ! -z "$(docker network ls -qf name=my-network)" ]; then
              docker network rm my-network
            fi
            
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_ID }}/tiki-taza
            
            sudo docker pull redis
            sudo docker network create my-network
            sudo docker run --name my-redis --network my-network -d redis
            sudo docker run -e SPRING_PROFILES_ACTIVE=prod -it -d -p 8080:8080 --name sponus-docker -e TZ=Asia/Seoul --network my-network ${{ secrets.DOCKER_USERNAME }}/sponus-docker

            docker system prune -f
