name: CI

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ## create application.yml
      - name: make application-secret.yml
        run: |
          mkdir -p ./api/src/main/resources
          touch ./api/src/main/resources/application-secret.yml
        shell: bash
      - name: deliver application-secret.yml
        run: echo "${{ secrets.APPLICATION_SECRET }}" > ./api/src/main/resources/application-secret.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test -i
